language: node_js

env:
  - DATABASE_URL || 'postgresql://yongama:pg123@localhost:5432/greetings_test'


  
node_js:  
  - "8.9.4"

before_script:
  - psql -c 'create database  greetings_test;' -U postgres
  - psql -U postgres -d greetings_test -a -f tables.sql

services:
  - postgresql